### ISSUE TITLE
Excluded Day - Tick to toggle the Combined Service

### ISSUE THREAD

**Issue by josephj** [efcsydney/efcsydney-roster#135]
As an admin user
I want to exclude a day as Combined Service by toggling a switch button instead of typing
so that I can save my time

**Comment by josephj** [comment]
**Acceptance Criteria**
* Ensure you can see SwitchButton on the Edit Day dialog
* Ensure you can toggle the Combined Service by switching the button.

**Sample URL**
http://demo-roster.efcsydney.org/#/

**Snapshot**
![image.png](https://images.zenhubusercontent.com/5a84b2194b5806bc2bc6faf8/93a89c83-3366-4a05-b354-7d4aeb2b5444)

**Pull request**
https://github.com/efcsydney/efcsydney-roster/pull/155/files

**Comment by james1239090** [comment]
Accepted
