### ISSUE TITLE
Manage roles

### ISSUE THREAD

**Issue by Josephu** [efcsydney/efcsydney-roster#151]
#### User Story
As an admin
I would like to create, update, and delete a position for a selected service 
so that I have the flexibility to assign different roles to different services

#### Notes
* Same API
* uses Front-end component

#### Possible Tasks
- [ ] UI - Form @sirjoe 

![image](https://user-images.githubusercontent.com/30176303/36932265-a1f6a0bc-1f1a-11e8-83e5-fe49a56e018f.png)

![image](https://user-images.githubusercontent.com/30176303/36932266-a5e998dc-1f1a-11e8-8de0-a407de3ce24a.png)

![image](https://user-images.githubusercontent.com/30176303/36932267-aa7f086e-1f1a-11e8-986f-d29ab37f8cc2.png)

**Comment by josephj** [comment]
@yhua045 

http://demo-roster.efcsydney.org/#/admin/edit/1

**Acceptance Criteria**
* Ensure you can add new position
* Ensure you can delete newly added position
* Ensure you can modify existing positions
