### ISSUE TITLE
Manage frequency

### ISSUE THREAD

**Issue by Josephu** [efcsydney/efcsydney-roster#152]
#### User Story
As an admin
I would like to set the frequency for a selected service
so that I have the flexibility to set dates for different services

#### Note
 * Data structure not too difficult
 * Focus on pre-populating dates
 * will discuss refactoring later
 * three different frequencies - Every Sunday / Every Saturday / Monthly

#### Possible Tasks
- [x] UI @One7Nine 

![image](https://user-images.githubusercontent.com/30176303/36932108-968eedf8-1f18-11e8-93de-58ce9c03427f.png)

![image](https://user-images.githubusercontent.com/30176303/36932112-9fcefbba-1f18-11e8-962a-ac71ff7b6dd2.png)

![image](https://user-images.githubusercontent.com/30176303/36932115-a65c4a82-1f18-11e8-9cee-80d0e757fe2d.png)

![image](https://user-images.githubusercontent.com/30176303/36932117-addf83fa-1f18-11e8-9a68-72350d77d245.png)

**Comment by One7Nine** [comment]
http://demo-roster.efcsydney.org/#/admin/edit/1

ensure you can see frequency droplist 
ensure you can change frequency status via choosing one of three options
