### ISSUE TITLE
3/27 Scrum Methodology 

### ISSUE THREAD

**Issue by josephj** [efcsydney/efcsydney-roster#159]
#### User Story
As a **Scrum Master**,
I want to **learn the fundamental Scrum methodology**
so that **I can apply the theory and use the tools to solve problems**.

#### Detailed Description
@james1239090 will study and share this topic on [27th March](https://calendar.google.com/event?action=TEMPLATE&tmeid=MG1lZmwzdTBpamlmOGNhbDYwMW5hNmJmbHJfMjAxODAzMjdUMDkzMDAwWiBkZXZlbG9wZXJAZWZjc3lkbmV5Lm9yZw&tmsrc=developer%40efcsydney.org). 

#### References
[What's the Difference? Agile vs Scrum vs Waterfall vs Kanban > Agile Methodology](https://www.smartsheet.com/agile-vs-scrum-vs-waterfall-vs-kanban#what-is-scrum)

**Comment by james1239090** [comment]
It is already finished.
