### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by One7Nine** [efcsydney/efcsydney-roster#164]
#### User Story
As an user
I would like my input data to be encrypted through HTTPs.

As an EFC Sydney IT Developer
I would like to have the HTTPs being enabled so that i can introduce Firebase redirection

#### Notes
  * AWS Certificate 
  * Need AWS Load Balancer - Free
  * Might be the blocker for the Firebase Integration

#### Possible Subtasks (Who?)
- [x] QA HTTPs, AWS ELB - @liam-lai                        
- [ ] Production HTTPs, AWS ELB - @liam-lai                   
- [ ] Auto Redirection from HTTP to HTTPs (Node.js Server) @yhua045

**Comment by josephj** [comment]
@liam-lai @yhua045                                               
We have 4 subtasks. It seems the estimation is too low. Let's discuss it tomorrow.
