### ISSUE TITLE
Listing

### ISSUE THREAD

**Issue by One7Nine** [efcsydney/efcsydney-roster#165]
#### User Story
As an admin
I would like to see existing categories so i can decide which category to modify.

#### Possible Subtasks
- [ ] UI @josephj 

![Admin_UI_Table.PNG](https://images.zenhubusercontent.com/5a9126554b5806bc2bc836b2/66b749ae-b9f9-4df9-92ff-0a5751b2298a)

![image](https://user-images.githubusercontent.com/30176303/36931988-4b11e71a-1f16-11e8-9537-1741bfe50fe0.png)

**Comment by josephj** [comment]
http://demo-roster.efcsydney.org/#/admin

![image.png](https://images.zenhubusercontent.com/5a84b2194b5806bc2bc6faf8/39f6a064-0800-49d2-b20f-f134b05dfa66)

**Comment by josephj** [comment]
@james1239090 

Can you help me to review the ticket?
