### ISSUE TITLE
(0.5) Footnote label changes to Description Label []

### ISSUE THREAD

**Issue by liam-lai** [efcsydney/efcsydney-roster#224]
#### User Story
As an admin I would like to see some improvements on the existing Edit Service so that the system get improvements according to the user feedback in the Sprint #3 Review Meeting

#### Acceptance Criteria
- [ ] Ensure that the “Footnote Label” label changes to “Description Label”

**Comment by josephj** [comment]
@liam-lai Don't forget to **merge your branch** and record the **used time**
