### ISSUE TITLE
(6) QuarterView - Render date rows with service frequency setting

### ISSUE THREAD

**Issue by james1239090** [efcsydney/efcsydney-roster#233]
#### User Story
As an admin, I would like to see some improvements on the existing Edit Service so that the system gets improvements according to the user feedback in the Sprint #3 Review Meeting

#### Acceptance Criteria
- [ ] Ensure using service API of frequency to render table row.

#### References

Wireframe? Mockup?

**Comment by yhua045** [comment]
@josephj @trust2065 

看起來都不錯 都工作

只剩一個小問題, 就是如果我先加了 footnote, 然後在同一天 再更新其他position的值, 上傳的serviceInfo裡面的 footnote 值會是空的, 這個問題可能跟這張 ticket沒有太大關係. 我可以開個新的 ticket 如果你覺得有需要的話

![image](https://user-images.githubusercontent.com/4614867/41486230-197163f8-7127-11e8-8347-a1e457fc3d80.png)
