### ISSUE TITLE
(5)Ensure that the Service Title, Note Label are mandatory.[1.5]

### ISSUE THREAD

**Issue by queenahu119** [efcsydney/efcsydney-roster#236]
#### User Story
As a user, I cannot click the "Save" button when the label fields are empty.

#### Acceptance Criteria
- [ ] Ensure the label fields are mandatory.

#### References
![45835011a37a4a9dbe8f5884bdee0c7b.png](https://images.zenhubusercontent.com/5abcb7d84b5806bc2bcce67d/d81fa138-c5ef-4fd3-b372-e7f6916d2a45)

**Comment by josephj** [comment]
@queenahu119  Please remember to update the time you spent on this ticket :)

`(4) ... [1.5]` Should be more than 1.5 I guess, right?
