### ISSUE TITLE
QuarterView - Render name cells properly with corresponded date and position

### ISSUE THREAD

**Issue by sirjoe** [efcsydney/efcsydney-roster#251]
#### User Story
As an **user**,
I would like to see the table populated with names that correspond to individual roles and dates

#### Acceptance Criteria
- [ ] Ensure the names are aligned with the roles on a given date.

**Comment by trust2065** [comment]
@james1239090 I think this issue can be solved while #233 is complete.
We should merge it to #233 or we can just close it.

![image](https://user-images.githubusercontent.com/13488449/40638330-0877ea0e-634e-11e8-9f70-9490b7548898.png)

![image](https://user-images.githubusercontent.com/13488449/40638326-001309ca-634e-11e8-8405-93a0dd9480bc.png)

**Comment by josephj** [comment]
This feature will be implemented in the #233
