### ISSUE TITLE
Dockerize - Auto build Docker Image via Travis-CI

### ISSUE THREAD

**Issue by BrandonTsai** [efcsydney/efcsydney-roster#260]
#### User Story
As a DevOps Engineer,
I would like to build docker image automatically via Travis-CI
so that reviewer could pull the image and run in the testing environment.

#### Acceptance Criteria
- [ ] Ensure docker image is pushed to DockerHub or AWS registry when the **qa** and **master** branch is updated.

**Comment by josephj** [comment]
@BrandonTsai Can we break this done to make it more feasible? Or we can spike for this feature first.
https://www.scaledagileframework.com/spikes/
