### ISSUE TITLE
Ticket Movement SOP

### ISSUE THREAD

**Issue by BrandonTsai** [efcsydney/efcsydney-roster#264]
#### User Story
As a trainer in EFC Sydney IT 
I would like to have a ticket movement SOP documentation 
so that the new developer could have the basic concept of Zenhub and ticket management.

#### Acceptance Criteria
- [x]  Ensure the documentation gets the correct workflow for the development.

#### References
https://paper.dropbox.com/doc/Ticket-Movement-SOP-otiecixAqrvK9QqMyukJc

**Comment by josephj** [comment]
@trust2065 

Can you help to review the documentation holistically again?
https://paper.dropbox.com/doc/Ticket-and-Branch-Workflow-otiecixAqrvK9QqMyukJc

**Comment by trust2065** [comment]
Will review it before this Thursday(17/May)
