### ISSUE TITLE
Schedule a session with user (Pongpong) to gather the requirements to further enhance current print feature

### ISSUE THREAD

**Issue by yhua045** [efcsydney/efcsydney-roster#549]
#### User Story
We need to gather the requirements to further enhance the print feature. The current print feature works well for English service but not Chinese service. It is unclear at this stage of what has been missing or lack of in the Chinese service print out. Therefore, we need to obtain some info to further enhance the print feature.

#### Acceptance Criteria
- [ ] Ensure

#### References

Wireframe? Mockup?

**Comment by josephj** [comment]
@yhua045 @ryrocks 

I've collected the necessary information from Pongpong.
Please let me know if you need me to clarify something. Thanks.
https://paper.dropbox.com/doc/--AR0G5~0FsorHelsRTewOZcOnAg-lYVojn8cJOsyvSocqn2FM
